version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - 5432:${DB_PORT}
    volumes:
      - budgeteer-db:/var/lib/postgresql/data 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:${ADMINER_PORT}

volumes:
  budgeteer-db: